twitter_consumer_key = 'API key'
twitter_consumer_secret = 'API secret key'
twitter_access_token = 'Access token'
twitter_access_token_secret = 'Access token secret'
youtube_api_key = 'YouTube Data API v3 Key'